apiVersion: kubeadm.k8s.io/v1beta1
kind: ClusterConfiguration
kubernetesVersion: stable
apiServer:
  certSANs:
  - "192.168.43.155"
networking:
  podSubnet: 192.168.0.0/16
controlPlaneEndpoint: "192.168.43.155:6443"
